// <auto-generated />
using GESTION_PAGOS;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace PRUEBA_OPERATI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PRUEBA_OPERATI.Entities.PotenciaParticipante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CapacidadDemandadaMW")
                        .HasColumnType("double precision");

                    b.Property<string>("Participante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RequisitoAnualMWAnio")
                        .HasColumnType("double precision");

                    b.Property<string>("Subcuenta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ValorRequisitoEficienteMWAnio")
                        .HasColumnType("double precision");

                    b.Property<string>("ZonaPotencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PotenciasParticipantes");
                });
#pragma warning restore 612, 618
        }
    }
}
